#ifndef PROBEACCURACYTEST_ALPHA_TEXTWRITE_H
#define PROBEACCURACYTEST_ALPHA_TEXTWRITE_H


void calcData(int stepData[11]);
void writeDataToFile(int stepData[11]);


#endif //PROBEACCURACYTEST_ALPHA_TEXTWRITE_H
